config setup
    charondebug="ike 1, knl 1, cfg 0"
    uniqueids=no

conn %default
    keyexchange=ikev2
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    authby=secret
    dpdaction=restart
    dpddelay=10s
    dpdtimeout=30s
    auto=start

conn aws-tunnel-1
    left=10.0.1.10
    leftid=54.151.194.132
    leftsubnet=0.0.0.0/0
    leftupdown=/etc/ipsec.d/vti1.sh
    right=18.141.117.198
    rightsubnet=0.0.0.0/0
    mark_out=100
